### ISSUE TITLE
Load arxiv author list from a separate json config file

### ISSUE THREAD

**Issue by yxjiang** [small-thinking/taotie#76]
Currently we config the arxiv author list from the .env file with the ARXIV_AUTHORS key. And the authors are separated by comma. Given the author list can be very long, this config would be hard to read.

Additionally, we would like to load the arxiv author list from a separate config file arxiv_author.json. The format of the json would be the following.

```
[
  "affiliation-1": ["author1", "author2"],
  "affiliation-2": ["author3", "author4", "author5"],
  "affiliation-3": ["author6", "author7", "author8"],
  ...
]
```

**Comment by wwzeng1** [comment]
Can you also use the example authors from .env.template instead of dummy variables like "author1"?
